#!/bin/sh
# SPDX-FileCopyrightText: © 2008-2022 Oprea Dan
# SPDX-FileCopyrightText: © 2008-2022 Bart de Koning
# SPDX-FileCopyrightText: © 2008-2022 Richard Bailey
# SPDX-FileCopyrightText: © 2008-2022 Germar Reitze
# SPDX-FileCopyrightText: © 2017 Matthias Gerstner
# SPDX-FileCopyrightText: © 2024 Jürgen Altfeld
# SPDX-FileCopyrightText: © 2024 Christian Buhtz <c.buhtz@posteo.jp>
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This file is part of the program "Back In Time" which is released under GNU
# General Public License v2 (GPLv2). See LICENSES directory or go to
# <https://spdx.org/licenses/GPL-2.0-or-later.html>.

# Location of this script
CUR_PATH="$(dirname $(readlink -m $0))"

# Was this script started in the source code folder (normally during development)?
# Prefer the repository 'common' folder if present. This ensures that
# relative paths like "test/config" resolve to the source tree when running
# from the repository root, while still allowing direct invocation of
# '/app/backintime.py' (used by some tests).
if [ -f "${CUR_PATH}/common/backintime.py" ]; then
  APP_PATH=$(readlink -m "${CUR_PATH}/common")
elif [ -f "${CUR_PATH}/backintime.py" ]; then
  APP_PATH=$CUR_PATH
else
  # CUR_PATH must be /usr/bin (the default installation path of this script)
  # or another sibling folder of "share" (in case of an alternative installation
  # folder like "/var/bin" where BiT must be installed into /var/share/backintime then)
  APP_PATH=$(readlink -m "${CUR_PATH}/../share/backintime/common")
fi

# -s Don't add user site directory to sys.path
# NOTE: Do NOT use -E here because it causes PYTHONPATH (used by tests
# and by running from source) to be ignored. Tests (and development
# workflows) rely on PYTHONPATH being propagated to subprocesses.
# TODO Should we use "$APP_PATH" (quoted) to prevent globbing and word splitting?
/usr/bin/python3 -s $APP_PATH/backintime.py "$@"
